{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.APN-Pucky",
    "module": "TULib",
    "version": "0.2.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "cmpdcnvgmbeg7d5o5pcuagylnu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TULib-0.2.14.jar",
          "url": "TULib-0.2.14.jar",
          "size": 1489062,
          "sha512": "5f247ef4be131bb76bcac37bb3536ff621740e70d609ef2b35fa12637f04f543279197ed4b978c75de537f32e205b28354bcac1b6752a5e825ab7fec353733fa",
          "sha256": "7a3a67395dcacd7e2525d1a89e92ed2cbaeaf32d48732809809a28b6999d1e97",
          "sha1": "b6cb82501c20ad058e5e11a42ec128ca81976d7b",
          "md5": "8360dc07bce8072e2d441dbf87e61913"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20190722"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.0.rc1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.11.0.rc1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "0.45"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "darklaf-core",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "com.github.iconloader",
          "module": "icon-loader",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "org.jdom",
          "module": "jdom2",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "com.esotericsoftware.yamlbeans",
          "module": "yamlbeans",
          "version": {
            "requires": "1.08"
          }
        }
      ],
      "files": [
        {
          "name": "TULib-0.2.14.jar",
          "url": "TULib-0.2.14.jar",
          "size": 1489062,
          "sha512": "5f247ef4be131bb76bcac37bb3536ff621740e70d609ef2b35fa12637f04f543279197ed4b978c75de537f32e205b28354bcac1b6752a5e825ab7fec353733fa",
          "sha256": "7a3a67395dcacd7e2525d1a89e92ed2cbaeaf32d48732809809a28b6999d1e97",
          "sha1": "b6cb82501c20ad058e5e11a42ec128ca81976d7b",
          "md5": "8360dc07bce8072e2d441dbf87e61913"
        }
      ]
    }
  ]
}
