{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.APN-Pucky",
    "module": "TULib",
    "version": "0.2.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "krcszzx2knd2tgi5tqfipik6xm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TULib-0.2.15.jar",
          "url": "TULib-0.2.15.jar",
          "size": 1489119,
          "sha512": "5e4a0a1243c42df472ce1c4305e4852535248afec35ec06e5c7463f91ffdac39d854743e721d2a60b99de541a37d1694c2b032fd4387e9d42e7a170376108493",
          "sha256": "f8711a494ed6709440f53c89dad56f004faaa23c7ac370c85c7fa09b66a0592c",
          "sha1": "95fefc24907164f0eea95f3608803084151171b8",
          "md5": "c14540293a9e3501c04567fc3a354cb6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20190722"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.0.rc1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.11.0.rc1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "0.45"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "darklaf-core",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "com.github.iconloader",
          "module": "icon-loader",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "org.jdom",
          "module": "jdom2",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "com.esotericsoftware.yamlbeans",
          "module": "yamlbeans",
          "version": {
            "requires": "1.08"
          }
        }
      ],
      "files": [
        {
          "name": "TULib-0.2.15.jar",
          "url": "TULib-0.2.15.jar",
          "size": 1489119,
          "sha512": "5e4a0a1243c42df472ce1c4305e4852535248afec35ec06e5c7463f91ffdac39d854743e721d2a60b99de541a37d1694c2b032fd4387e9d42e7a170376108493",
          "sha256": "f8711a494ed6709440f53c89dad56f004faaa23c7ac370c85c7fa09b66a0592c",
          "sha1": "95fefc24907164f0eea95f3608803084151171b8",
          "md5": "c14540293a9e3501c04567fc3a354cb6"
        }
      ]
    }
  ]
}
