{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.APN-Pucky",
    "module": "TUR",
    "version": "0.2.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "ixiyul36bzeuloex3froahxleu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TUR-0.2.22.jar",
          "url": "TUR-0.2.22.jar",
          "size": 45500,
          "sha512": "1f3bf2c01e1388be9c7aeeada355ebe6a98a0a6672100aa5b9e99ef160f40c38c2cc318ecf0f4d21d4a938be0fec384e2117fb6e22fab8d730c6508928ef908a",
          "sha256": "421f22996c5569737772d188b77336f9c19779237543774ded4b3996716fcbce",
          "sha1": "81bf005f584f3781d4f8cca015cd3157d90decf2",
          "md5": "4834c14d4cb61fb77eab3745c66651d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20190722"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.0.rc1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.11.0.rc1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "0.45"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "darklaf-core",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "com.github.iconloader",
          "module": "icon-loader",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "org.jdom",
          "module": "jdom2",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "com.esotericsoftware.yamlbeans",
          "module": "yamlbeans",
          "version": {
            "requires": "1.08"
          }
        },
        {
          "group": "com.github.APN-Pucky",
          "module": "GitJarUpdate",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "com.github.APN-Pucky",
          "module": "TULib",
          "version": {
            "requires": "0.2.15"
          }
        }
      ],
      "files": [
        {
          "name": "TUR-0.2.22.jar",
          "url": "TUR-0.2.22.jar",
          "size": 45500,
          "sha512": "1f3bf2c01e1388be9c7aeeada355ebe6a98a0a6672100aa5b9e99ef160f40c38c2cc318ecf0f4d21d4a938be0fec384e2117fb6e22fab8d730c6508928ef908a",
          "sha256": "421f22996c5569737772d188b77336f9c19779237543774ded4b3996716fcbce",
          "sha1": "81bf005f584f3781d4f8cca015cd3157d90decf2",
          "md5": "4834c14d4cb61fb77eab3745c66651d9"
        }
      ]
    }
  ]
}
