{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.APN-Pucky",
    "module": "TUR",
    "version": "0.2.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "cfjtdiirgbblnoiupjy5zabeoe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TUR-0.2.21.jar",
          "url": "TUR-0.2.21.jar",
          "size": 45500,
          "sha512": "b58eea747ff969be0af34354cd73f83e99b909a91638400a4c26add0e168164b93c201b45131d98a776f38ff57d470777e8d65e4deaccd1f615442f03b39e5da",
          "sha256": "ad1e095d6f922ac143adb4df999df6da39d0e6078a076cee5c35d633ccbc6b42",
          "sha1": "ad1e3314a2323cbe3d0c27e416aff0792a93aa5b",
          "md5": "b9feafb7c1d262d2fc66c1b955cccfc3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20190722"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.0.rc1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.11.0.rc1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "0.45"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "darklaf-core",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "com.github.iconloader",
          "module": "icon-loader",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "org.jdom",
          "module": "jdom2",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "com.esotericsoftware.yamlbeans",
          "module": "yamlbeans",
          "version": {
            "requires": "1.08"
          }
        },
        {
          "group": "com.github.APN-Pucky",
          "module": "GitJarUpdate",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "com.github.APN-Pucky",
          "module": "TULib",
          "version": {
            "requires": "0.2.15"
          }
        }
      ],
      "files": [
        {
          "name": "TUR-0.2.21.jar",
          "url": "TUR-0.2.21.jar",
          "size": 45500,
          "sha512": "b58eea747ff969be0af34354cd73f83e99b909a91638400a4c26add0e168164b93c201b45131d98a776f38ff57d470777e8d65e4deaccd1f615442f03b39e5da",
          "sha256": "ad1e095d6f922ac143adb4df999df6da39d0e6078a076cee5c35d633ccbc6b42",
          "sha1": "ad1e3314a2323cbe3d0c27e416aff0792a93aa5b",
          "md5": "b9feafb7c1d262d2fc66c1b955cccfc3"
        }
      ]
    }
  ]
}
