{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.APN-Pucky",
    "module": "TUR",
    "version": "0.2.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "ve7wxrbypvcsllcr6dixmp5plq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TUR-0.2.23.jar",
          "url": "TUR-0.2.23.jar",
          "size": 45500,
          "sha512": "6cd490e27aba4056fb7268cb99943ff6a07c4c39c28d53b4acac1ce347439f826e13e2052d13ae85127fe77a775084282e270547d3f2689d63d1836d535d356e",
          "sha256": "512143a021e6a698678589de4233f3c22e14d1aa907e70e27ffe72470a51c94d",
          "sha1": "8b7edcd78145575f796594b381fa627ce441341e",
          "md5": "5e93fb31817a334e8d66f035de871b37"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20190722"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.0.rc1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.11.0.rc1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "0.45"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "darklaf-core",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "com.github.iconloader",
          "module": "icon-loader",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "org.jdom",
          "module": "jdom2",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "com.esotericsoftware.yamlbeans",
          "module": "yamlbeans",
          "version": {
            "requires": "1.08"
          }
        },
        {
          "group": "com.github.APN-Pucky",
          "module": "GitJarUpdate",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "com.github.APN-Pucky",
          "module": "TULib",
          "version": {
            "requires": "0.2.16"
          }
        }
      ],
      "files": [
        {
          "name": "TUR-0.2.23.jar",
          "url": "TUR-0.2.23.jar",
          "size": 45500,
          "sha512": "6cd490e27aba4056fb7268cb99943ff6a07c4c39c28d53b4acac1ce347439f826e13e2052d13ae85127fe77a775084282e270547d3f2689d63d1836d535d356e",
          "sha256": "512143a021e6a698678589de4233f3c22e14d1aa907e70e27ffe72470a51c94d",
          "sha1": "8b7edcd78145575f796594b381fa627ce441341e",
          "md5": "5e93fb31817a334e8d66f035de871b37"
        }
      ]
    }
  ]
}
