{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.APN-Pucky",
    "module": "TUR",
    "version": "0.2.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "pl54wr7xpzhtjnb3gdb5t7tvdy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TUR-0.2.20.jar",
          "url": "TUR-0.2.20.jar",
          "size": 45089,
          "sha512": "9261fd911c2050dfb33abc40ff00ac93ee67f044f3167b8cbecf4d21dd8fa1ab91d815c53a11c5cc70a6d537ec20f1eed33979445ac51aa00f69b9e1ae0235ae",
          "sha256": "b84d9e54f3d0705444bd1e52475597d242824a1bc5c9b76df02bfbced57086ed",
          "sha1": "ae52858eeb5b83cc8357550b933df2865fcab3fd",
          "md5": "26da7fe7366b7ad9f955c0594423c236"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20190722"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.0.rc1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.11.0.rc1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "0.45"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "darklaf-core",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "com.github.iconloader",
          "module": "icon-loader",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "org.jdom",
          "module": "jdom2",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "com.esotericsoftware.yamlbeans",
          "module": "yamlbeans",
          "version": {
            "requires": "1.08"
          }
        },
        {
          "group": "com.github.APN-Pucky",
          "module": "GitJarUpdate",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "com.github.APN-Pucky",
          "module": "TULib",
          "version": {
            "requires": "0.2.14"
          }
        }
      ],
      "files": [
        {
          "name": "TUR-0.2.20.jar",
          "url": "TUR-0.2.20.jar",
          "size": 45089,
          "sha512": "9261fd911c2050dfb33abc40ff00ac93ee67f044f3167b8cbecf4d21dd8fa1ab91d815c53a11c5cc70a6d537ec20f1eed33979445ac51aa00f69b9e1ae0235ae",
          "sha256": "b84d9e54f3d0705444bd1e52475597d242824a1bc5c9b76df02bfbced57086ed",
          "sha1": "ae52858eeb5b83cc8357550b933df2865fcab3fd",
          "md5": "26da7fe7366b7ad9f955c0594423c236"
        }
      ]
    }
  ]
}
